### ISSUE TITLE
Weird FOUC on production site

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#117]
There is some weird flash of unstyled content when loading the site without cache. I suspect it's either the cookiebot script blocker or the service worker. Needs more investigation.

**Comment by MattIPv4** [comment]
@pjeweb Are you still seeing this, since both cookiebot and the root SW are gone now?

**Comment by pjeweb** [comment]
no, all gone. it was hard to reproduce but it did definitely still occur with SW and not anymore without. I think the registration could in some cases block css. but unless we want to go full-PWA we dont really need to worry about that
