### ISSUE TITLE
"Explore Alveus"

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#14]
Here are some ideas we had for the "Explore" section of the website:

# Ambassador

- [ ] Text search for ambassadors
- [x] Have some UI to give a better overview of Ambassadors and their Enclosures, for example grouping Parrots etc. to prevent a very long list of ambassadors
- [x] Embed/Link Videos, Clips, Reels etc.
- [x] crosslink to Enclosure
- [ ] more educational content (how to help, diet, enrichment, FAQ)

# Enclosures & Facilities

- [ ] Add pages for Enclosures & Facilities (Infos like cost, sponsors etc,; linking to ambassadors; link/embed Alveus tour video with timestamps; maybe even 360° image)

**Comment by pjeweb** [comment]
Some layout idea how it could look like:

![explore-alveus](https://user-images.githubusercontent.com/684458/227623313-d9588f8e-536f-4d06-9f0a-75e9c1dfe71c.jpg)

**Comment by pjeweb** [comment]
The berlin zoo has a toggle for the animals (grouped by enclosure | all animals):

![enclosures](https://user-images.githubusercontent.com/684458/229297860-e4e2b580-92eb-41fd-83b5-2d79c02e7c34.png)
![animals](https://user-images.githubusercontent.com/684458/229297862-d94e183c-0aef-4c7c-be3c-344a77662a7f.png)


Also some inspiration for the facts per ambassador:
![facts1](https://user-images.githubusercontent.com/684458/229297923-29df7ef2-8642-423b-a812-d0d6d7002efc.png)
![facts2](https://user-images.githubusercontent.com/684458/229297925-6ec5d90d-f498-4fdb-9772-af3cae65d580.png)

**Comment by MattIPv4** [comment]
@pjeweb do you think we can close this out? I think we've probably done everything here we're going to do? Alveus' focus is very much on the individual ambassadors, so I don't think we need to build out a deeper enclosure-based UI.
