### ISSUE TITLE
Add ambassador images to animal quest

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#159]
Idea from @pjeweb:

![image](https://user-images.githubusercontent.com/12371363/230532939-7515b2b4-7b6c-4236-9482-f01bffc4f016.png)

If we do it, we need to consider how it handles episodes with multiple ambassadors (I'm thinking picture-in-picture bubbles of different sizes), and what to do for the Falcon episode (I'm thinking just show a translucent version of the thumbnail image).

**Comment by MattIPv4** [comment]
@pjeweb thoughts about how to approach on mobile? I feel it kinda needs to wrap, but it doesn't look great?

![image](https://user-images.githubusercontent.com/12371363/230634679-66e158f0-9d0e-4b14-8866-589a3b29fa6c.png)

**Comment by pjeweb** [comment]
I dont have a silver bullet but a combination of smaller font, making the play button smaller and the photo smaller might work. Btw. totally love the second ambassador bubble.

![alveusgg_aq_image_mobile](https://user-images.githubusercontent.com/684458/230637293-a662791a-51c3-48e9-a2a3-d507a39b9d04.png)
