### ISSUE TITLE
Leaves colliding with content

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#170]
At certain breakpoints, the decorative leaves are colliding with the content:

![image](https://user-images.githubusercontent.com/12371363/230700216-6f879291-4ce7-47c1-879c-1db79a81f5f0.png)

Worst at about `1300px` and `1050px`.

**Comment by MattIPv4** [comment]
Also an issue on the ambassadors page, at a wide range of viewports:

![image](https://user-images.githubusercontent.com/12371363/230700801-51f3ae57-85ed-4d0a-9780-8cba2e5b20b2.png)

**Comment by MattIPv4** [comment]
My initial thought for solving this is just to shrink the leaves enough so that they only ever sit within the whitespace between the text in the sections, so they still span the section changes nicely, but don't interfere with the content.

**Comment by pjeweb** [comment]
yeah that seems to be the obvious solution. might look dumb if the padding is very small. we could increase the padding but that seems like a lot of work or just hide the leaves in that case?

![leave-small](https://user-images.githubusercontent.com/684458/230723580-09cb1c0a-7805-45be-be06-47b4b11d3038.png)

**Comment by pjeweb** [comment]
oh i misunderstood you. yeah if we can move and scale them to fit the gaps that would be great

**Comment by MattIPv4** [comment]
Yeah, move it down vertically a bit and then scale so it fits between the two sections
