### ISSUE TITLE
Hamburger menu disappears on contact page

### ISSUE THREAD

**Issue by naomi-lgbt** [alveusgg/alveusgg#173]
The hamburger menu doesn't seem to be present on the contact page.

![SmartSelect_20230407_231159_Chrome.jpg](https://user-images.githubusercontent.com/63889819/230706529-dd000d3c-be6b-4876-a0e6-7ba46fdc9d8e.jpg)

**Comment by pjeweb** [comment]
Thank you for the report! It looks like you are still getting the old site. It may take some time for the DNS change to propagate through to you.

It's supposed to look like this:
![alveus-contact-mobile](https://user-images.githubusercontent.com/684458/230718610-8908d600-47d8-4789-88c5-9b9888ec6547.png)
