### ISSUE TITLE
Redirects for ambassadors

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#178]
I think it would be nice to have `/x` redirect to `/ambassadors/x` so we could link them in SE commands etc.

With the .gg domain: `https://alveus.gg/fenn`

**Comment by MattIPv4** [comment]
We could add a fallback redirect from `/x` to `/ambassadors/x`, but I'm not sure we want that? I think it'd be safer to define redirects specifically for the actual ambassador slugs.

To do that though, we'd need to pull from `data/ambassadors.ts` into `next.config.mjs`, which won't work as it's a TypeScript file, and it has image imports.

@pjeweb what do you think is the best solution there? Do we have a JS file that just contains the ambassador names, that `next.config.mjs` and `data/ambassadors.ts` both consume?

**Comment by pjeweb** [comment]
Can we do a combination of `getStaticPaths` and redirect with `getStaticProps`? https://nextjs.org/docs/api-reference/data-fetching/get-static-props#redirect

**Comment by MattIPv4** [comment]
Ahh yes I forgot you could do that, let me try it and see how that plays out
