### ISSUE TITLE
Add and link guidestar/candid "seal of transparency"

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#180]
Add to the footer or somewhere on the about pages?!

https://help.guidestar.org/en/articles/2160518-how-to-add-a-candid-participation-logo-to-a-website

**Comment by MattIPv4** [comment]
The footer is starting to get a bit crowded, but putting it on the about page makes sense to me -- maybe a new section in there that links to the annual reports, talks about donations and this badge?

**Comment by pjeweb** [comment]
One way that seems pretty common is to have a page "Finances" with the guidestar link, 990 forms and annual reports on it, but maybe alveus does not like that because they don't want the info graphic "annual report" to be placed under Finances?

here are some examples I found:
https://shywolfsanctuary.org/about-us/our-finances/
https://www.primaterescue.org/financials/

Alveus does publish their form 990's on their guidestar profile, maybe we could link that on that page as well, if they want that.
