### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#191]
Do we want unit/integration tests?

I think we don't need automated tests for most parts of the website, but maybe for:
- web push (vapid, content encryption etc.)
- data encryption for database

If so, i would probably go with vitest (see https://github.com/vercel/next.js/tree/canary/examples/with-vitest ).

if we want want end-to-end tests i would probably go with playwright (see https://github.com/vercel/next.js/tree/canary/examples/with-playwright ).

**Comment by pjeweb** [comment]
Working on tests with vitest in #192 (for db encryption)

**Comment by MattIPv4** [comment]
Having some testing in place for specific things like encryption or push logic is probably worth it -- not so sure about whether its worth having anything done with playwright, the footprint of the site isn't too large where you're likely to break pages by updating a shared component.
