### ISSUE TITLE
Fix eslint rules complaining about aliased import order

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#194]
Imho its wrong that eslint wants relative import before aliased "absolute" imports:

Currently:
```typescript
import from '../path/to.ts';

import from '@/path/to.ts';
```

I want:
```typescript
import from '@/path/to.ts';

import from '../path/to.ts';
```

**Comment by MattIPv4** [comment]
+1 to doing this, order groups should let you do it: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#options
