### ISSUE TITLE
Small styling inconsistencies

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#198]
- [x] External links in Show and Tell should be styled like other external links
- [x] Hover style: Use slight zoom for ambassadors
- [ ] Show and Tell dates are formatted based on the users locale, other dates are always formatted in US style

**Comment by MattIPv4** [comment]
👀 Tackling the hover style issue

**Comment by MattIPv4** [comment]
> Show and Tell dates are formatted based on the users locale, other dates are always formatted in US style

What's the preferred thing here, should everything use the localdate component, or should we just stick to doing US style everywhere (which I imagine is actually easier for folks to compensate for than being unsure if something is actually local or not)

**Comment by pjeweb** [comment]
Yeah probably the same long form US format everywhere.
