### ISSUE TITLE
Lightbox caption for collabs could be nicer

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#207]
I think this could use formatting:
<img width="1083" alt="collabs-date" src="https://user-images.githubusercontent.com/684458/232352023-f73fda3d-398f-42e8-a043-6e91e915a266.png">

https://github.com/alveusgg/alveusgg/blob/d2b0f496990e34e574c16b6d8d0cf6c0362c8296/apps/website/src/pages/collaborations.tsx#L134

Probably the same formatting as in the heading (`{formatDateUTC(value.date, "long")}`).

**Comment by MattIPv4** [comment]
Ah yup -- that date value used to be a string but I changed it to a Date obj and clearly forgot to format it there
