### ISSUE TITLE
Idea: Blog style content

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#211]
This is probably not feasible, but it would be great for SEO and "old people" to have a few blog posts about events or just repurposing social media content or stream content. Maybe we have someone in the community that likes to write?

(this overlaps a bit with AQ transcripts, newsletter and FAQ)

**Comment by MattIPv4** [comment]
@pjeweb Worth closing? I think this would probably come from Alveus if it were to happen, rather than us?
