### ISSUE TITLE
Disable scrolling in show and tell fullscreen

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#224]
- Disable the ability to scroll when in fullscreen on show and tell
- Add new click regions at the top/bottom of the screen (where you can just see the next/previous posts), which change post like the existing up/down buttons
- Extra points: When the user tries to scroll up/down, make the click regions and/or the buttons highlighted as a visual prompt

**Comment by pjeweb** [comment]
i think the "seen on stream" badges also force overflow on the slides which makes the experience extra bad

**Comment by pjeweb** [comment]
Thanks for working on this. Let me know if I can help. YT and TT both allow scrolling on desktop and it feels similar. They also have arrow buttons.

<table>
<tr><td><img src="https://user-images.githubusercontent.com/684458/234059137-8b13146a-c4bd-4278-84bd-80fae0c1ade4.png" width="350"><td><img src="https://user-images.githubusercontent.com/684458/234059157-9f2fb38a-b7a0-41a4-ae58-c7ac3fb45471.png" width="350">
<tr><td>tiktok<td>youtube
</table>

I also thought it might be an idea to have a help overlay that you can dismiss that explains how to use the mode? or is that cringe?

![help-overlay](https://user-images.githubusercontent.com/684458/234059880-c3bac506-d26f-4112-aa32-13235851141b.png)
