### ISSUE TITLE
Notifications: Push Notifications to Twitter via API

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#242]

**Comment by MattIPv4** [comment]
@pjeweb I don't think this is worth doing? Mik handles pushing updates to socials okay, and they get used more as an upcoming announcement thing, rather than the in-the-moment style that notifications are?

**Comment by pjeweb** [comment]
> @pjeweb I don't think this is worth doing? Mik handles pushing updates to socials okay, and they get used more as an upcoming announcement thing, rather than the in-the-moment style that notifications are?

I mean we do support the announcements with push and on the site, but yeah they dont really get used.
