### ISSUE TITLE
Idea: Hover Cards for Ambassadors and Staff (and maybe enclosures)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#246]
Show a small popover when hovering Ambassadors or Staff members when linked similar to user profiles and channel handles in stream titles on twitch and user cards on discord.

Use cases: Animal Quest, maybe Updates Page?!

**Comment by jinitsuga** [comment]
Hello! I'd love to work on this  -- assuming the card design idea could maybe be a smaller version of the info found on /ambassadors/name, correct?
I don't see specific info/page for enclosures when hovering here:
![image](https://github.com/alveusgg/alveusgg/assets/73081185/8b927ccc-8cfe-460e-8074-91ce08b7e453)
, but maybe they could be created along the cards themselves :)

**Comment by MattIPv4** [comment]
Yah, I think an ambassador hover card would have a small picture of the ambassador to one side, and then their name + species + enclosure (I think that'd be the most useful info at a glance)

For the enclosure hover cards, I think it'd just be great to show a row of pictures for the ambassadors that are in that enclosure.

**Comment by MattIPv4** [comment]
In terms of code structure, I think it'd be great to have a generic hover card component that can be placed inside any link, and then have specific versions that use that component for enclosures + ambassadors

**Comment by jinitsuga** [comment]
A generic hover card component is exactly what I had in mind, so it's there for reusability if other things come up as well. Potentially with an indicator to what type of card (ambassador/staff/enclosures) it'll be and the specifics via props.

**Comment by jinitsuga** [comment]
Also thinking there should be a very slight delay before the card shows for better UX.

**Comment by MattIPv4** [comment]
100% -- I would make sure the card is a dynamic component, and add a small delay on hover before we start attempting to fetch or show it. No point bogging down the initial page load with the extra data.

**Comment by MattIPv4** [comment]
Closing, I don't think this is worth the effort, folks are used to clicking on things on the internet for more info.
