### ISSUE TITLE
Implement privacy-friendly analytics/view statistics

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#266]
# Proposal

My proposal is to set up our own instance of Plausible (https://github.com/plausible/analytics). It is available as OSS for self-hosting, designed to be privacy friendly. It does not use cookies and does not track beyond a very basic anonymized hash that is used to count unique visitors per day.  https://plausible.io/privacy-focused-web-analytics

# Frontend

The tracking consists of a small ~1kb script that can be cached and an event endpoint. Both can be proxied through the edge network. (see https://github.com/alveusgg/alveusgg/pull/264/commits/e2b7a5eb61d77e4446224dcce55d004e2d309390) 

# Backend

We can either use the plausible UI directly with user/password logins or we can embed the dashboard for one site in the admin panel (see https://github.com/alveusgg/alveusgg/pull/264/commits/53afef4dfd719ae5f7f92e145bfa6f42714b8aa9). The authentication is through a secret get parameter that is provided as a server environment variable and passed to the admin page, if the user has appropriate permissions and is authenticated through the site auth (currently using Twitch OAuth). This also means that the secret can be extracted by a malicious or compromised user with permissions to view the stats. If that comes to be known, we would need to revoke the share link in the plausible UI and generate a new secret. Considering there are no personal or PII data accessible through the plausible embed, that risk seems tolerable.

#  Hosting

Right now I have set up a docker compose deployment on a Hetzner Cloud instance, hosting plausible and its dependencies (postgres and clickhouse) as suggested at https://plausible.io/docs/self-hosting. Additionally I have set up nginx, certbot and watchtower in docker compose for https, caching and automatic updates: https://github.com/alveusgg/plausible-hosting

I am not sure how much traffic we should expect and how big to scale the server. The Hetzner cloud instance (Ampere arm64, 8 core, 16 gig, 160 gb nvme ssd, Ubuntu 22.04) can be scaled to 16 cores/32 gig. If that is not enough we would have to move hosting/servers or split the system into multiple machines. Firewall, snapshots and backups are set up in hetzner cloud.

These instances are only available in their german data center, which is good for GDPR, but not the best for access times from the US. It is however a very small async payload that should not block any user interaction, so i do not think that really matters.

I am open for any other suggestions for hosting.

We can also buy this service or any other analytics SaaS, but that comes with its own cost and privacy concerns.

# Privacy Policy / Consent

Imho we should not need explicit consent as we do not collect any PII and the raw visit stats should fall under "legitimate interest". We should however mention it in the privacy policy.  (see https://github.com/alveusgg/alveusgg/pull/264/commits/eaf8b6da8790841a31a528d7652ebad578348dcf)

# Future ideas

Some of the next things would be to look into tracking redirects to external sites without a page visit, possibly with an edge middleware using the plausible API. https://plausible.io/docs/events-api

-------------------------

PR #264

**Comment by pjeweb** [comment]
This looks like an interesting alternative that might be hostable right on vercel with the website: https://github.com/umami-software/umami

**Comment by MattIPv4** [comment]
My gut says Plausible is probably the right choice, at least for now -- it's relatively popular, so, in terms of privacy and compliance, we get some innate protection as there are larger entities than us that'd be using it.

That being said, has Vercel's own analytics been looked at? I believe they're roughly the same level of GDPR-compliance as Plausible, but would be out of the box while the site is running on them?

**Comment by pjeweb** [comment]
I was under the impression that it's quite expensive, but looking at the Pro plan we already have we get 25k "events" and 100k/14$. So unless we get more than 125k page views and other events, it's not more expensive than hosting plausible. I don't really have a feeling for how many views the site gets though.
https://vercel.com/docs/concepts/analytics/limits-and-pricing

Otherwise I have not looked deeper into it, but I will.

**Comment by MattIPv4** [comment]
Maybe we enable it for a couple of days under what we get for free with the Pro plan, and gauge what traffic looks like and how much it might cost us? Does Vercel allow limits to be set on how much we might spend if the site were to get a wave of traffic?

**Comment by MattIPv4** [comment]
(Fwiw I am probably inclined to stick with Plausible over Vercel though -- it does put us at more risk as we'd be the ones storing the tracking data, but I imagine in the long-run it'll be much more cost-effective, especially if the site were to grow or get request spikes etc.)
