### ISSUE TITLE
CI with Github Actions?

### ISSUE THREAD

**Issue by jontok** [alveusgg/alveusgg#276]
Hey i just recently discovered Alveus and now want to help with the best of my capabilities. Since i am an DevOps Enginieer by profession, this seems like a good opportunity to support the Sanctuary.

I have seen some workflow runs in one branch which seemingly where only for testing. It could be possible to use parts of the test workflow depending on your current deployment setup.

**Comment by MattIPv4** [comment]
👋 Hey, welcome!

Our deployments all happen via Vercel, so there's no need for GitHub Actions in that flow (Vercel detects all pushes to any branch and will trigger a deployment, be that a branch preview or production).

We don't have any tests in main currently, so there hasn't been a need for an Actions workflow at present. #134 will introduce some unit tests for notifications-related functionality, and includes an Actions workflow that will run those tests.

**Comment by jontok** [comment]
Alright, closing this issue since there is no need for GitHub Actions workflows atm
