### ISSUE TITLE
VOD (YT) overview

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#31]
Add an overview of the (latest) VOD's or other Playlists

**Comment by ACA30** [comment]
Where might this be included on the site (what page/location on that page)?

What VODs should be included as well? [This playlist](https://www.youtube.com/playlist?list=PL-Upt2azOK-P7YXytLPhUUy76bdP3a6Xy) is decent for Maya's Alveus-related content, but doesn't include collabs or streams on the Alveus channel

**Comment by MattIPv4** [comment]
I think a route like /live/archive or /live/previous might be apt for this.

As for what VODs should be included -- I think the primary thing to include would be VODs from the Alveus channel, as this is what the site is for. I do agree it probably makes sense to also include VODs from Maya as well when she's doing an Alveus stream.

**Comment by MattIPv4** [comment]
Perhaps we could also feature recent uploads from Mik's Alveus Highlights channel too? (and with that in mind, I think /live/archive is probably a clearer URL over /live/previous)

**Comment by ACA30** [comment]
Yeah agreed on `/live/archive` - I think it's definitely more clear

Only potential issue I see with Alveus Highlights channel is I'm not sure if we want to include clips in the main feed?

Maybe having multiple feeds makes sense? Something like
- VODs
- collabs
- clips

Mik's channel could cover things like clips/collabs, but I don't actually know of a channel uploading relevant VODs from /alveussanctuary (unless you mean like a feed of the Twitch VODs themselves, or Mik will upload them on the Highlights channel?)

If go the route of multiple feeds on the highlights channel, having Mik also manage the playlists as they upload would probably be the easiest route?

**Comment by pjeweb** [comment]
If we want to automatically archive twitch vods on a yt channel we can take a look at this repo: https://github.com/TimIsOverpowered/archive/blob/main/src/middleware/twitch.js

**Comment by MattIPv4** [comment]
Does it really make sense to have continual archives now that's its 24/7 live cams? To me, feels better to just let Mik etc. preserve VoDs for specific things that happen that aren't the live cams

**Comment by pjeweb** [comment]
If there is a working workflow for archiving streams, then no. I also do not think archiving every minute would make much sense.

But that repo actually seems to have figured out access to the chapters/comments. That way we could theoretically automate splitting the vod and only upload interesting parts?! But maybe Mik already has something working for that? Plus I would want to track stream segments anyways via title changes etc.

**Comment by MattIPv4** [comment]
Closing in favour of #636
