### ISSUE TITLE
Replace Prisma with Drizzle

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#320]
Consider replacing Prisma with Drizzle ORM + Kit as it could reduce cold start times and can run in edge runtimes. We tested drizzle orm in #306 on the chatbot.

- orm: https://orm.drizzle.team/docs/quick-start
- migrations: https://orm.drizzle.team/kit-docs/overview
- with planetscales http https://orm.drizzle.team/docs/installation-and-db-connection/mysql/planetscale

**Comment by pjeweb** [comment]
We should keep and eye on what prisma will do, since they know about the downsides of the big runtime and missing edge runtime support and might change that:
https://github.com/prisma/prisma/issues/18763

**Comment by tomheaton** [comment]
happy to help out with this!

**Comment by pjeweb** [comment]
That would be great if you are up for it. But beware there is quite a bit of prisma code in already and I'm not sure if everything translates easily to drizzle!?

**Comment by tomheaton** [comment]
Yeah there is a lot so I'll do it incrementally so the Prisma all still works.
My Discord is `tomheaton` if you want to talk about any of this in more detail! 😄

**Comment by pjeweb** [comment]
I think we will hold on this for now. Prisma is making a few efforts to alleviate its problems so we will probably stick with it for now.

**Comment by tomheaton** [comment]
sounds like a good idea, hopefully prisma is on the right track
