### ISSUE TITLE
Looking to help out

### ISSUE THREAD

**Issue by nslee333** [alveusgg/alveusgg#340]
Hey, 

Do y'all have a specific issue that might be a good first issue? I looked through and couldn't find issues labeled with that. 

The one's that I was looking at was either helping with tasks on #79 or looking into #313.

I'm a newer self-taught dev trying to gain experience, and I'd rather work on real projects than toy ones :)

**Comment by nslee333** [comment]
@MattIPv4 @pjeweb

**Comment by MattIPv4** [comment]
Sorry for not responding sooner. I don't really have any specific recommendations, but the two you linked definitely seem to be on the easier end to implement. With #79 I would make sure to post in the issue with what you want to work on specifically before you start, so we can make sure we're on the same page.

**Comment by nslee333** [comment]
Okay sounds good, thanks.
