### ISSUE TITLE
[Bug]: Build failure while starting dev server

### ISSUE THREAD

**Issue by nslee333** [alveusgg/alveusgg#356]
### What is the current behavior?

Following the setting up the local development environment guide [here](https://github.com/nslee333/alveusgg/tree/main#local-development).

While trying to start the dev server I get this issue:

localhost:3000:

    Failed to compile
    ./src/assets/socials/georgie-reel-clip.mp4?quality=low
    NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object]
    This error occurred during the build process and can only be dismissed by fixing the error.

Browser Console:

    GET http://localhost:3000/ 500 (Internal Server Error)
  
    Uncaught ModuleBuildError: Module build failed (from ./build-scripts/video-loader.cjs):
    NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object]
        at processResult (:3000/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:394733)
        at :3000/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:396519
        at :3000/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8645
        at :3000/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5828
        at r.callback (:3000/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)
        at :3000/home/nslee333/test4/alveusgg/apps/website/build-scripts/video-loader.cjs:404:7
        at processResult (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:394733)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:396519)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8645)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5828)
        at r.callback (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)
        at <unknown> (/home/nslee333/test4/alveusgg/apps/website/build-scripts/video-loader.cjs:404:7)
        at processResult (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:394802)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:396519)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8645)
        at <unknown> (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5828)
        at r.callback (/home/nslee333/test4/alveusgg/node_modules/.pnpm/next@13.4.4_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4039)
        at <unknown> (/home/nslee333/test4/alveusgg/apps/website/build-scripts/video-loader.cjs:404:7)
  
    src/assets/socials/georgie-reel-clip.mp4?quality=low
    NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object]
    console.error @ client.js:1
    window.console.error @ next-dev.js:27
    handleErrors @ hot-dev-client.js:131
    processMessage @ hot-dev-client.js:202
    eval @ hot-dev-client.js:50
    eval @ websocket.js:58
    handleMessage @ websocket.js:57

WSL Ubuntu: I get this error about x4

    │ Processing video /home/nslee333/test4/alveusgg/apps/website/src/assets/socials/georgie-reel-clip.mp4 ...
    │  ... /home/nslee333/test4/alveusgg/apps/website/src/assets/socials/georgie-reel-clip.mp4 failed {
    │   error: Error: Command failed: "/home/nslee333/test4/alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/linux-x64/ffprobe"…
    │   /bin/sh: 1: /home/nslee333/test4/alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/linux-x64/ffprobe: Permission denied
    │
    │       at ChildProcess.exithandler (node:child_process:419:12)
    │       at ChildProcess.emit (node:events:513:28)
    │       at maybeClose (node:internal/child_process:1091:16)
    │       at Socket.<anonymous> (node:internal/child_process:449:11)
    │       at Socket.emit (node:events:513:28)
    │       at Pipe.<anonymous> (node:net:322:12) {
    │     code: 126,
    │     killed: false,
    │     signal: null,
    │     cmd: '"/home/nslee333/test4/alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/linux-x64/ffprobe" -v error -select_stre…
    │   },
    │   stdout: '',
    │   stderr: '/bin/sh: 1: /home/nslee333/test4/alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/linux-x64/ffprobe: Permissio…
    │ }
    │ - error ./src/assets/socials/georgie-reel-clip.mp4?quality=low
    │ NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object]
    │ Import trace for requested module:
    │ ./src/assets/socials/georgie-reel-clip.mp4?quality=low
    │ ./src/components/layout/footer/Socials.tsx
    │ ./src/components/layout/footer/Footer.tsx
    │ ./src/components/layout/Layout.tsx
    └─ Failed in 6m 0.3s 
    ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @alveusgg/alveusgg-website@0.1.0 dev: `run-p build:manifest dev:*` Command failed with signal "SIGINT"

### What is the expected behavior?

The expected behavior is that it launches the dev server and website without errors.

### Steps to reproduce

git clone the alveusgg repo, and follow setup steps.

### Browser specs

https://www.whatsmybrowser.org/b/WTBQ3

### Anything else?

I've gotten it to work on one repo where it launched fine seemingly random from a clone, but the latest ones have been having the same issue.

Current attempts I've taken to fix this issue:
1. Start a fresh clone to my machine in a new directory and try again.
    - From Alveusgg and personal fork of the repo.
2. Deleted and started a new .env with fresh variables.
3. Deleted all node_module folders, reinstall and rebuild.
4. Compared working repo with the faulty repo using diff, no difference.
5. Inspected the permissions of the @ffprobe and @ffmprobe, in the working and faulty repo, permissions exactly the same.
6. Attempted to use `sudo pnpm run -r dev`, -> `pnpm command not found`

The other ideas that I could have is unisnstalling pnpm and reinstalling it.

System info:

    wsl -l -v
      NAME                   STATE           VERSION
    * Ubuntu                 Running         2
      docker-desktop-data    Stopped         2
      docker-desktop         Stopped         2

**Comment by pjeweb** [comment]
I'm getting similar but different errors with ffprobe on `pnpm dev` under MacOS now too, but different ones. I'll look into it a bit. They dont seem to matter though. The site and videos are still loading …

```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/ffprobe/index' in /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts for build dependencies doesn't lead to expected result '/Users/pje/Sites/alveusgg/alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/ffprobe/index.js', but to '/Users/pje/Sites/alveusgg/alveusgg/apps/website/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/ffprobe/index.js' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 .pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/ffprobe/index
<w>  at file dependencies /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at file /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at resolve commonjs /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '.pnpm/@ffmpeg-installer+ffmpeg@1.1.0/node_modules/@ffmpeg-installer/ffmpeg/index' in /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts for build dependencies doesn't lead to expected result '/Users/pje/Sites/alveusgg/alveusgg/node_modules/.pnpm/@ffmpeg-installer+ffmpeg@1.1.0/node_modules/@ffmpeg-installer/ffmpeg/index.js', but to '/Users/pje/Sites/alveusgg/alveusgg/apps/website/node_modules/.pnpm/@ffmpeg-installer+ffmpeg@1.1.0/node_modules/@ffmpeg-installer/ffmpeg/index.js' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 .pnpm/@ffmpeg-installer+ffmpeg@1.1.0/node_modules/@ffmpeg-installer/ffmpeg/index
<w>  at file dependencies /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at file /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at resolve commonjs /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '.pnpm/loader-utils@3.2.1/node_modules/loader-utils/lib/index' in /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts for build dependencies doesn't lead to expected result '/Users/pje/Sites/alveusgg/alveusgg/node_modules/.pnpm/loader-utils@3.2.1/node_modules/loader-utils/lib/index.js', but to '/Users/pje/Sites/alveusgg/alveusgg/apps/website/node_modules/.pnpm/loader-utils@3.2.1/node_modules/loader-utils/lib/index.js' instead. Resolving dependencies are ignored for this path.
<w>  at unknown 4 .pnpm/loader-utils@3.2.1/node_modules/loader-utils/lib/index
<w>  at file dependencies /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at file /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
<w>  at resolve commonjs /Users/pje/Sites/alveusgg/alveusgg/apps/website/build-scripts/video-loader.cjs
```

**Comment by nslee333** [comment]
Yeah it's weird, I'm going to keep trying stuff, I'll post any updates.

**Comment by nslee333** [comment]
I got a clone to randomly work after I uninstalled and reinstalled pnpm, but after the first success, the issue started up again.

**Comment by nslee333** [comment]
I got a clone to randomly work after I uninstalled and reinstalled pnpm, but after the first success, the issue started up again.

Do you have any idea for me to try @MattIPv4 ?

**Comment by MattIPv4** [comment]
I'm really not sure, sorry. This feels like an odd permissions issue with WSL, which isn't uncommon due to how WSL wraps stuff.

**Comment by nslee333** [comment]
It's all good, might need to go back to using git bash and cmd, wish I had a mac tbh

**Comment by nslee333** [comment]
Update: I got it working, it apparently ffprobe didn't have executable permissions, seems fairly obvious looking back now.

Unless @pjeweb wants me to reopen it, I'm probably just going to close this issue

Here's a reference for how I solved it for anyone referencing this issue:
WSL2 Ubuntu
Followed alveusgg/node_modules/.pnpm/@ffprobe-installer+ffprobe@2.0.0/node_modules/@ffprobe-installer/linux-x64/ffprobe
`ls -l` to inspect if it had executable permission:
`-rw-r--r-- 3 nslee333 nslee333 78392768 Jul 24 14:22 ffprobe`

ran `chmod +x ffprobe`
`-rwxr-xr-x 3 nslee333 nslee333 78392768 Jul 24 14:22 ffprobe`

Reran `pnpn run -r dev` at project root and it worked.
