### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#36]
# Short-term

- [x] Define roles in code as needed ("show-and-tell", "notifications", ...)
- [x] Allow super users to assign/remove roles to users (once logged in)

**Comment by pjeweb** [comment]
Resolved in #74

**Comment by JonasFranke** [comment]
https://github.com/alveusgg/alveusgg/blob/main/apps/website/src/server/twitch/sync-roles.ts says to implement this. #74 seems not to
