### ISSUE TITLE
[Bug]: Show and Tell loses scroll position when new posts are approved and then refocusing page

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#379]
### What is the current behavior?

When you visit `/show-and-tell`, then a new post gets approved, you change the tab/window and lose focus, then open the page again your scroll position will be off because the new posts are loaded.

### What is the expected behavior?

New posts are **not** loaded on refocus and the scroll position is kept.

### Steps to reproduce

See current behaviour

### Browser specs

n/a

### Anything else?

`refetchOnWindowFocus` should probably be set to `false` for the infinite query (https://tanstack.com/query/latest/docs/react/reference/useQuery)

**Comment by okGus** [comment]
Hello, I'm new to open source contribution and wanted to help in some way, I was looking at this and wanted to know if the scroll position can be also be seen when "Load more" is clicked on /show-and-tell?

**Comment by pjeweb** [comment]
> Hello, I'm new to open source contribution and wanted to help in some way, I was looking at this and wanted to know if the scroll position can be also be seen when "Load more" is clicked on /show-and-tell?

I'm not sure, I follow. The "load more" feature uses tanstack query's (aka react-query) `useInfiniteQuery`. That uses cursors to get the next page (https://tanstack.com/query/v4/docs/react/guides/infinite-queries). That should ensure there are no gaps. It's not based on number offsets, but the ids.

Loading a new page should afaik not invalidate the first page's data. But im not 100% sure. Maybe the docs answer that? Would be nice to check.

I think the (bigger) problem is that it invalidates when you refocus the window.

**Comment by okGus** [comment]
Before: scroll position is off after losing focus
[before](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExanduZzdlcm44ZHA3aGJvbmQwdTlyeWdjZXdycXdtbzBlaDdsbGc4diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/S0y9ngjaOZmRQldVgT/giphy.gif)

After: scroll position is kept after losing focus
[after](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3ZzNjY1M3c5ZWtkZzhvdjdwbXhqNDRpdm9zZW9xdXNyNmd4NDkwYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/47cu2LmdrVQqynxTOk/giphy.gif)

This would be the correct behavior in the after correct?

**Comment by pjeweb** [comment]
I think the before/after videos are mixed up but yes, in that case we'd also want to keep the scroll position. Good catch. Happy to accept a fix for that!
