### ISSUE TITLE
Cleanup Twitch API (Event Subs etc.) that are not being used

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#383]
> There are also a few twitch (API) features that we do not use (using the event sub etc.). We do not really use them. That might be another PR though as I might take a moment to cut that out cleanly.

_Originally posted by @pjeweb in https://github.com/alveusgg/alveusgg/issues/382#issuecomment-1693860633_

**Comment by JonasFranke** [comment]
I‘d do that if nobody else is working on that

**Comment by pjeweb** [comment]
Happy for you to try. It might be pretty difficult though, because the features are spread throughout the code base.

Some pointers:

- these can probably go https://github.com/alveusgg/alveusgg/tree/main/apps/website/src/server/twitch
- and the commented out config for those tasks: https://github.com/alveusgg/alveusgg/blob/main/apps/website/src/config/scheduled-tasks.ts
- and the env vars `TWITCH_EVENTSUB_`
- so can the webhook endpoint https://github.com/alveusgg/alveusgg/tree/main/apps/website/src/pages/api/webhooks/twitch
- probably a bunch in this file can go, but not everything as thats still used for the giveaway checks etc https://github.com/alveusgg/alveusgg/blob/main/apps/website/src/server/utils/twitch-api.ts
- there might be more
