### ISSUE TITLE
[Idea]: Searchable clips (with user voting)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#411]
### Describe your idea / enhancement

Implement a system for logged in users to submit and vote clips from the alveus twitch channel.

Use cases MVP:

- Everyone:
  - View clips [new, top all time, top 24h, top 7d, top 30d, top year]
  - View a clip (twitch embed, votes, submitter, creator, timestamp/relative time)
- Logged in:
  - Submit a clip
	  - Check its a valid clip and broadcaster_id is alveus or maya?! => https://dev.twitch.tv/docs/api/reference/#get-clips
	  - Only allow submitting a clip once
	  - Save to database
  - Upvote a clip (only upvote?) -> save to database (and maybe kv)
- Admin:
  - Maybe allow deleting submitted clips (without deleting the twitch clip)
- Background tasks:
  - Check if a clip has been deleted (twitch webhook and/or cronjob)

Use cases optional:

- "Hot" clips algorithm
- Discover mode (show random clips) (encourage voting, but do not show vote count before)
- Leaderboard / Awards for top submitters
- Credit clippers/submitters with points (see #24)
  - Problem: Fighting over internet points (submitter vs. clipper) -> clipper should probably get the credit
- Bookmark clips for your own use
- Search clips by title
- Search clips by tags
- Search clips by transcript
- Allow a list of source vods from other twitch channels for clips (for collabs)
- Allow YT clips
- Allow YT shorts
- Allow IG reels
- Allow TikTok videos
- Make clips sharable?! (deep links)

Prior art:

- https://smashscene.com/alveus
- https://github.com/JakeMiki/twitch-clip-queue

User feedback:

- On mobile its hard to get you own clips you've made (http://clips.twitch.tv/my-clips)

### How would this idea / enhancement be beneficial?

Helps discover clips for visitors and media production, encourages clipping, allows crediting clippers with the credit system when implemented.

-----------------------

### Discussed in https://github.com/orgs/alveusgg/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **pjeweb** December 14, 2022</sup>
</div>

**Comment by ExperimentalCyborg** [comment]
+ hide votes on a clip for the first X hours after submitting
+ log referrer HTTP header value (if any was set) for every page visit and for every vote (to be able to detect brigading and potentially roll back votes)

**Comment by pjeweb** [comment]
tagging could be used to fill the video/clips section on the ambassador pages

**Comment by pjeweb** [comment]
Community list of clips: https://docs.google.com/spreadsheets/d/1j6U_Z07TLIVQ9JNTVIwuKHFzLr5Nojei7JBrZe6nfv8/edit#gid=134037914
