### ISSUE TITLE
[Idea]: Make collabs sortable

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#427]
### Describe your idea / enhancement

Similar to ambassadors it would be great to be able to sort the collabs by name, maybe add a text search (suggested by josh_raiden in twitch chat)

### How would this idea / enhancement be beneficial?

Helps find collabs

**Comment by MattIPv4** [comment]
Text search seems a bit redundant to me, almost all browsers have that functionality built-in. Allowing sorting by oldest instead of newest seems sensible to me though. Anything else you think would make sense to sort by?

**Comment by pjeweb** [comment]
> Text search seems a bit redundant to me, almost all browsers have that functionality built-in.

Thats fair, although i think a dedicated search makes it easier for less advanced users and on mobile devices, but def. not as important.

> Anything else you think would make sense to sort by?

Can't really think of much else other than date and name. Sorting by length or "vod vs. video" does not really make much sense imo.

Not sure if we think thats good, but we could sort them by "relevance" as bad as that sounds. Having Ludwig up at the top would probably be good 🤷 


PS: I might open another issue, but it might be nice to have a small overview of all collabs without having to scroll down (maybe just the collaborators' profile pics?). The two column layout also looks great, but makes it a bit harder to scan fast.  But thats a different story.

**Comment by MattIPv4** [comment]
> Not sure if we think thats good, but we could sort them by "relevance". As bad as that sounds, having Ludwig up at the top would probably be good 🤷

We could probably do a sort based on following, so its an actual measurable metric. Might be something to run past Alveus folks before we do though, 'cause I'm not sure its the greatest look to have that.



> PS: I might open another issue, but it might be nice to have a small overview of all collabs without having to scroll down (maybe just the collaborators' profile pics?). The two column layout also looks great, but makes it a bit harder to scan fast. But thats a different story.

Sounds like a good idea to me, to improve navigation as the page gets longer and longer.
