### ISSUE TITLE
Fall carnival: Virtual tickets

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#430]
Implement #409 for the Fall Carnival 2023

# Views/routes

- `/events/fall-carnival-2023` Event page with editor (editor requires log in)
- `/events/fall-carnival-2023/tickets/hellsatanx` Customized ticket url to share

# Questions

- Do we need to check if users are banned and not allow banned users to create tickets?

# MVP

- Assets:
    - Ticket
       - [x] Base layer
       - [x] Mask
       - [x] Overlay (Text "Alveus Fall Carnival", "Nov. 4th 2023", "twitch.tv/maya")
       - [ ] attribute sticker artists on the ticket
	- [ ] Sticker set "Fall carvinal"
		- [x] pumkin(s)
		- [x] emojiconmotes (ambassadors)?
		- [x] more ideas are welcome Smile
- Ticket editor
   - [x] Place stickers (keep in bounds)
   - [x] Move stickers
   - [x] Remove stickers
   - [x] Support mobile and desktop
   - [x] reset button
   - [x] group stickers (by type/art style)
   - [x] attribute artists for stickers
- [x] DB table (`user_id`, `event`, `signup_at`, `customized_ticket_data`, ...)
- [x] Serialize custom ticket (-> save to db)
- [x] Rasterize custom ticket (-> save jpeg/png on cdn)
- [ ] QR-Code / Overlay for stream "Claim your custom Alveus Fall Carnival Ticket"
- [ ] Implement event page
    - [x] "Alveus Fall Carvinal, November 4th 2023, on twitch.tv/maya"
    - [x] More info about the event? Link to other events?
    - [x] not logged in -> "Log in with Twitch to claim a ticket"
    - [x] logged in -> "Customize a ticket"
- [ ] Implement ticket customization page
    - [x] Embed editor (see above)
    - [x] Share Button (Link-URL, Socials, E-Mail?)
    - [x] Download (-> jpeg/png)
- [ ] Implement ticket view
    - [x] Either load bitmap from cdn or render ticket from db
    - [x] Support og to share on socials. Make sure the image loads fast!
    - [x] if not customized -> "This person has not claimed their ticket yet" or "404 not found"
    - [x] if customized -> show readonly ticket of that person
    - [x] Repeat the buttons from the event page (Log in & Claim your own ticket / Customize your own ticket)
    - [x] On mobile: either allow to zoom the ticket on mobile or make sure it does at least work okay on vertical smartphone screens?!

# Ideas

- Event page
    - [ ] Add to calendar button?
    - [ ] Remind me -> Notification Bell Button?
- [ ] Generate QR-Code for customized ticket (`https://alveus.gg/events/fall-carnival-2023/tickets/{username}`)
- Ticket customization page
    - [ ] Maybe a delete button?
- More pages
    - [ ] my tickets (see #42 )
    - [ ] gallery of the tickets generated for one event
- Editor features:
    - [ ] scale ticket on mobile (pinch to zoom) to make placing stickers easier
    - [ ] resize stickers
    - [ ] rotate stickers
    - [ ] use stickers multiple times
    - [ ] move stickers in z-index
    - [ ] drag stickers from the pack to the ticket

**Comment by MattIPv4** [comment]
> * Does it make sense to render the ticket in the browser and store the data serialized in the db or should be prefer a bitmap for display?

I would think it makes more sense to store serialized data and render client-side when needed, rather than having to store a whole bunch of pre-rendered rasters in the DB? I think it probably is also safer from an abuse point of view if we're just storing some data we can validate rather than an arbitrary bitmap?

As for the storage medium, I think using the DB is probably fine -- we can load the data from the DB on the client-side via an API call, if needed to keep the page load time fast? That being said, I think just fetching from the DB, with a bit of caching in Next.js for the page, should be fine?

**Comment by pjeweb** [comment]
Yeah no i did not want to safe the bitmap in the db and we definitely want the sticker data in db. I typed that weird. We also definitely need bitmaps for the og and/or download. That point was supposed to be just about displaying the customized tickets in the browser where we dont really need it to be client side rendered for editing, so we could just use a bitmap.

**Comment by MattIPv4** [comment]
If we store the sticker data, could we use something like Satori to render it at edge?

**Comment by pjeweb** [comment]
> If we store the sticker data, could we use something like Satori to render it at edge?

yeah exactly
