### ISSUE TITLE
[Idea]: Admin/mod tool - Add short Links

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#464]
### Describe your idea / enhancement

Manage short links that redirect to an url thru the admin panel. Could be external sites or pages.

We probably still prefer next redirects if possible, but for quick things having a GUI would be nice.

Maybe also support giving uploaded images a short link (see #287)

Track clicks (counting/aggregating over time).

### How would this idea / enhancement be beneficial?

Better links to share (instead of long or changing external urls)

**Comment by JonasFranke** [comment]
I‘ll do it!
I‘d do it with a Next.js dynamic route and save all the redirected URLs in the db.

**Comment by JonasFranke** [comment]
@pjeweb How would you implement the link usage tracking feature? Just update an int in the database, or do we have better tools for this?
