### ISSUE TITLE
[Idea]: Improved commands list

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#487]
To expand on #475, we could add:
- copy command to clipboard on click
- tooltip for detailed explanation (but what would we want to explain?)

_Originally posted by @pjeweb in https://github.com/alveusgg/alveusgg/issues/475#issuecomment-1858888848_

**Comment by Benascor** [comment]
So I think I can implement the _copy to clipboard on click_ bit of this, but I'm not sure what we would want the tooltips to do here.

**Comment by pjeweb** [comment]
@Benascor agreed.

I think @sougataghar477 wanted to work on extending the commands page (not with these features but as described in #487), but i have not seen anything about it since. i'll ask if they are still working on it. 

The copy to clipboard feature could be helpful in anyways. Maybe we can extract the feature into its own effect or component. We have something similar here already: https://github.com/alveusgg/alveusgg/blob/d7fec53a984518fbd6800681445e910cb6cbed53/apps/website/src/components/shared/ShareButton.tsx#L71-L112

**Comment by Benascor** [comment]
@pjeweb alright sounds good. I was looking at something like this but I'm not sure how well it would work for the whole page. https://stackoverflow.com/questions/45071353/copy-text-string-on-click

**Comment by sougataghar477** [comment]
@Benascor let me work on it
