### ISSUE TITLE
Prefer alveus.gg over www.alveus.gg

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#49]
With a short TLD, and a short domain, it feels cleaner to me that we'd prefer using `alveus.gg` rather than `www.alveus.gg`. Thoughts?

**Comment by pjeweb** [comment]
Since Chrome and Safar hide the `www.` I did not mind as much, but I agree, without www. is better. I'll change that!

**Comment by pjeweb** [comment]
Should be resolved.
