### ISSUE TITLE
[Idea]: Link to the YT live stream (and chat)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#497]
### Describe your idea / enhancement

This probably needs access to the YT API to get the livestreams. Would be nice in the frontend and as short links (`alveus.gg/yt-live` and `alveus.gg/yt-chat`)

### How would this idea / enhancement be beneficial?

Improve discovery of YT stream and chat

**Comment by MattIPv4** [comment]
For shortlinks, I've been thinking about doing:

- /live > Twitch
- /live/twitch > Twitch
- /live/youtube > YouTube

You could then extend that with your chat idea to be /live/youtube/chat maybe?

**Comment by pjeweb** [comment]
Okay since `https://youtube.com/@alveussanctuary/live` works for live and we don't need the API for that i would not add it just for the chat link.

`/live/youtube` is good!

**Comment by pjeweb** [comment]
> We could essentially mirror that in the nav, with Live being a link to Twitch but also a dropdown on hover with those two links?
Oh right yeah. Maybe with a split button? Live (-> Twitch) and Dropdown in one? On hover works too.
