### ISSUE TITLE
[Idea]: WWF 'Give an Hour' tracking for Show and Tell

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#509]
### Describe your idea / enhancement

On Show and Tell submissions, from March 1st through to April 22nd, enable a checkbox for users to indicate their submission was a 'Give an Hour' activity, and if checked show an input for how many hours were spent on the activity.

On the Show and Tell homepage, from March 1st through to April 22nd, show a progress bar at the top for total hours spent as part of 'Give an Hour', ideally as a progress bar that automatically picks a target based on the current total.

Aim to keep the internal naming generic, as it is likely that after April 22nd we may want to switch this over to a more generic wording that allows folks to mark their submissions as general volunteering, so we can track activity from the community on an on-going basis.

### How would this idea / enhancement be beneficial?

Supporting WWF + Give an Hour, encouraging volunteering and other related activities.

**Comment by pjeweb** [comment]
Do we not want a more separate page just for Earth Hour with the progress bar, general infos, and "actions you can take"?

**Comment by MattIPv4** [comment]
Yah, I suspect an information page would be beneficial as well -- perhaps the progress bar + CAT on the main Show and Tell page, which links out to the info page with the progress bar again and all the info?

![image](https://github.com/alveusgg/alveusgg/assets/12371363/f1e0a19d-2e22-41cf-bea8-1102040a03e4)

**Comment by MattIPv4** [comment]
UI has been implemented, just the backend work needs to be done now to enable the submission UI to actually parse the user input and store it as part of the submission, and for the progress bar to pull the total from the DB
