### ISSUE TITLE
New alveus cam presets

### ISSUE THREAD

**Issue by loganrx8** [alveusgg/alveusgg#510]
### Describe your idea / enhancement

The following presets need to be added to the commands/presets page on the site. 

Marmoset:

- rightshelves - Shelves to the left of the door
- rightshelveslow - Shelves to the left of the door low 

Pasture:
- barn2w - barn2 wide 
- purplenest - purple martin nest
- purplebase - base of purple martin nest
- fencenear - near fence
- fencefar -  far fence
- Angel - feeder but slightly lower 

Foxes: 
- hillrightw - hill right wide

Marmosetindoor:
- cornershelf - far corner shelf

### How would this idea / enhancement be beneficial?

Make the Commands/Presets page up to date again.

**Comment by KnayteXX** [comment]
Added 2 presets to pasture:

1. feederinspect - looks at feeder output for clogs
2. bughunt - Quick starting point for bug hunts (inside barn, floor of food stall)

**Comment by dansza1** [comment]
Pasture:

- barn2r - in between barn2 and grove
- trailerleft - left of the trailer

Parrots:

- littelsbowl2 - bowl bottom right of the littles tree
- littlesb - bottom of the littles tree

**Comment by merger3** [comment]
Marmoset Outdoor:
- leftpostshelves - Shelves beneath the left platform
