### ISSUE TITLE
Replace wordpress site (alveussanctuary.org)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#52]
# Pre-Checklist

- [x] configure .org domain in vercel => vercel wont set up the domain unless the dns points to it ...
- [x] ~~google analytics tag~~
- [x] invite space to all teams (vercel, DO, planetscale, github)
- [x] make a list of services with their costs
- [x] lower TTL in DNS
- [x] `s/Alveus.gg/Alveus/` => #107
- [x] Sitemap?
- [ ] Alveus/Space has to set up a twitch dev account to use for OAuth
- [x] Replace alveussanctuary.org link with copyright smallprint in page footer
- [x] use .org privacy policy and check whats missing
- [x] Add .org to OAuth app

# Go-Live-Checklist

- [x] Add .org in Vercel
- [x] Unset `NEXT_PUBLIC_NOINDEX` for production
- [x] Update `NEXT_PUBLIC_BASE_URL`, `NEXT_PUBLIC_VERCEL_URL`, `VERCEL_URL` for production
- [x] Change DNS records

| Type | Name | Value |
| --- | --- | --- |
| `CNAME` | `www` | `cname.vercel-dns.com.` |
| `A` | `@` | `76.76.21.21` |
| `A` | `www` | **remove if set** |
| `AAAA` | `www` | **remove if set** |
| `AAAA` | `@` | **remove if set** |

- [ ] Check OAuth and S3 uploads work with .org domain
- [x] Check robots.txt, noindex etc.
- [x] Check top google search results still resolve correctly

# Move over website content

- [x] Home page
- [x] About pages
- [x] Ambassadors -> Replace with something based on the Twitch Extension?
- [x] Show and Tell ->  in progress, #5 
- [x] Events -> This probably needs to be reconsidered. The last "big" event was 2021 ... Maybe we can have some sort of blog-ish documentation for events still? Needs more thinking
- [x] Contact Us -> Does this need to a main menu item? Can we move this to the footer?
- [x] Donate -> Needs to be redone. I would prefer not to have so many different looking embeds, also amazon smile is sunsetting.
- [x] Merch -> Would be nice to have a nice Merch scroller of the SE Shopify merch as wenn as the plushies

**Comment by MattIPv4** [comment]
After a bit of back and forth, _our_ current idea is:

```
Home (will be similar to the current Alveus homepage imo, but with a player on the right and a CTA to /live?)
Watch
Explore (for community/educational items)
  - Ambassadors
  - Show and Tell
  - Schedule
  - etc...
About (for formal items)
  - Alveus
  - Maya
  - etc...
Support (maybe just have these items both be top-level)
  - Donate
  - Merch
Notification bell icon
Account icon (or profile picture)
```

This would enable us to have all the content under a single site, while serving the existing purpose of the main website but bringing in more community-centric things like the /live page.

**Comment by MattIPv4** [comment]
@pjeweb Is this issue in need of an update now that everything from the old site is implemented, essentially just capturing how/when the switch-over should happen now?

**Comment by pjeweb** [comment]
> @pjeweb Is this issue in need of an update now that everything from the old site is implemented, essentially just capturing how/when the switch-over should happen now?

i've updated the issue, feel free to add anything i missed

**Comment by MattIPv4** [comment]
We're live 🎉
