### ISSUE TITLE
Mobile App (iOS/Android)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#54]
Do we see any benefit in a "real" app published to the app stores (iOS/Android)?

# Alternative

- No apps
- Progressive Web App ("Add to home page", "Install") 

# Prior art

- "Cohhilition Mobile" (CohhCarnage) https://play.google.com/store/apps/details?id=com.cohhilition.cohhcarnage_mobile&hl=gsw&gl=US

# Tech

- Capacitor/Tauri to wrap a web app
- React native (Expo)
- Native (SwiftUI/Kotlin)
- Flutter

# Problems

- Apple requires a dev fee (100 USD/y)
- Store registration is a lot of work

**Comment by MattIPv4** [comment]
I would lean into going down the PWA route if we do have a need for a more "app-like" experience, rather than shipping a dedicated app. That being said, I'm not sure I overly see the need for an app currently, but maybe it'll become more of a priority down the road?

**Comment by MattIPv4** [comment]
@pjeweb are we good to close this out given the PWA has been serving us well, and Apple _isn't_ going to kill them now?

**Comment by pjeweb** [comment]
agreed
