### ISSUE TITLE
[Idea]: Redirect 404's in /admin/ to the login

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#567]
### Describe your idea / enhancement

I purposely made admin links show the default 404 page for "security" reasons. I do now think its way better UX if we can use deep links to admin features and admins being asked to log in and since its all open source its not really a big security feature anyways.

It could also be a "not authorized" page with a login button.

### How would this idea / enhancement be beneficial?

Allow deep linking to admin features without showing an error page if the users are not logged in.

**Comment by JonasFranke** [comment]
I'd like to do that
