### ISSUE TITLE
[Idea]: Provide alternative to Planetscale for (free) dev setup

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#586]
### Describe your idea / enhancement

Since Planetscale will drop the free plan in a month, I suggest we find another (free) suggestion for contributors. Could be a local db (#81) or maybe we try to migrate to Vercel's Postgres aka neon which is (still) free.

### How would this idea / enhancement be beneficial?

Do not make contributing and local development harder.

**Comment by MattIPv4** [comment]
+1 to using Vercel's postgres for prod etc., and we can provide a docker-compose with a postgres image for local dev

**Comment by MattIPv4** [comment]
https://neon.tech/docs/guides/vercel

**Comment by MattIPv4** [comment]
cc https://github.com/alveusgg/alveusgg/issues/82 + https://github.com/alveusgg/alveusgg/issues/81
