### ISSUE TITLE
[Idea]: Add toggle for local/Alveus time on updates calendar

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#592]
> I also tried to add a toggle to show in Alveus time (CT) _or_ local time.

_Originally posted by @pjeweb in https://github.com/alveusgg/alveusgg/pull/587#pullrequestreview-1926321755_

**Comment by MattIPv4** [comment]
Relevant bits of code:

The admin panel month selection + event fetching:

https://github.com/alveusgg/alveusgg/blob/5ca12a4afaa74d5d7abe052109deb7b934d57e1d/apps/website/src/components/admin/calendar-events/CalendarEvents.tsx#L14-L62

The public calendar month selection + event fetching:

https://github.com/alveusgg/alveusgg/blob/5ca12a4afaa74d5d7abe052109deb7b934d57e1d/apps/website/src/components/notifications/Schedule.tsx#L10-L60

The calendar rendering itself:

https://github.com/alveusgg/alveusgg/blob/5ca12a4afaa74d5d7abe052109deb7b934d57e1d/apps/website/src/components/content/Calendar.tsx#L71-L225

**Comment by ExperimentalCyborg** [comment]
I'll give it a shot this weekend / next week 🫡

**Comment by ExperimentalCyborg** [comment]
Work stuff came up, it'll be Soon™

**Comment by pjeweb** [comment]
Another idea would be to link to a page where you can see the time in all timezones?! Eg https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240530T10

**Comment by ExperimentalCyborg** [comment]
Nah i just need to get out of my ADHD procrastination cycle and actually do the thing properly 🥲

React is new to me but as a Professional Software Developer™ that shouldn't be an issue
