### ISSUE TITLE
[Bug]: Docker compose minio doesn't start on Arch Linux

### ISSUE THREAD

**Issue by JonasFranke** [alveusgg/alveusgg#628]
### What is the current behavior?

MinIO exits after starting setup with
```
website-s3-1  | /opt/bitnami/scripts/libminio.sh: line 364: /bitnami/minio/data/.root_user: Permission denied
website-s3-1 exited with code 1
```

### What is the expected behavior?

MinIO starts without errors

### Steps to reproduce

```bash
docker compose up
```

### Anything else?

I found [this](https://stackoverflow.com/questions/72332735/minio-permission-denied) in a quick search.

**Comment by MattIPv4** [comment]
Swapping to a Docker volume sounds like the easiest cross-platform solution here.
