### ISSUE TITLE
Idea: Collabs overview, link videos

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#63]
I would propose a page or a section on a page dedicated to all collabs with a thumbnail and a link to the video/vod. Maybe we could fit the 2021 halloween event in there somehow :)

For the design I was pretty much thinking we copy youtube playlists view.

**Comment by MattIPv4** [comment]
So https://alveus.gg/about/alveus should have a collaboration section (I left a TODO comment), mirroring the current site: https://www.alveussanctuary.org/about-alveus/

I do wonder though if a dedicated page under the proposed `Explore` dropdown might be better for discoverability? And maybe it could be titled something more generic (though not sure what the word would be) to capture events + collabs?

**Comment by pjeweb** [comment]
Oh I did not know. Yeah depending on how full the dropdowns get, I would like it up there.

**Comment by MattIPv4** [comment]
https://github.com/alveusgg/alveusgg/pull/70 + https://github.com/alveusgg/alveusgg/pull/66
