### ISSUE TITLE
[Idea]: Social/video feed section

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#635]
### Describe your idea / enhancement

I think having a section of current instagram posts or youtube videos could be nice. The shop has that for example. Not sure where it would fit.

IG feed:

![ig-feed](https://github.com/alveusgg/alveusgg/assets/684458/ba44562d-2495-4040-8c62-dc3335d54300)

Youtube feed:

![videos](https://github.com/alveusgg/alveusgg/assets/684458/a7d656df-5f1a-4c87-be0c-6aff4db0233d)

### How would this idea / enhancement be beneficial?

Not 100% if its a good idea. We already have a lot of content, so adding more might not be the best idea, but I think it would present more of the (good) socials content on the site and could drive cross-platform engagement.

**Comment by MattIPv4** [comment]
I like this idea in principle, but struggle to see where it'd fit into the site and make sense 🤔
