### ISSUE TITLE
[Idea]: Add Missing Step for iOS to Notification Popup 

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#637]
### Describe your idea / enhancement

The notification bell popup should show a third step explaining you need to open the PWA when added to Home Screen and press the bell again to get push notifications.

### How would this idea / enhancement be beneficial?

Improve UX for iOS users

**Comment by bl4nkfce** [comment]
There's also some small CSS issues with this popup - the content overflows the popup.
Take a look at the screenshot below.

The content container has a dynamic max-width based on vw (80vw - 50px), and the content has a min-width set to 300px, which causes the overflow on some screens (tested on iphone 14 and iphone 15 simulators)

![safari_ios_iphone_14_simulator](https://github.com/alveusgg/alveusgg/assets/26897688/f546258d-2e2e-4e6b-8f2a-ab4507623ac4)

**Comment by bl4nkfce** [comment]
@pjeweb
I can take care of this - I'll add the missing step to the guide and adjust the popup styles slightly on smaller screens.

**Comment by pjeweb** [comment]
> @pjeweb I can take care of this - I'll add the missing step to the guide and adjust the popup styles slightly on smaller screens.

that would be great! thank you!
