### ISSUE TITLE
[Idea]: Document additional commands

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#638]
### Describe your idea / enhancement

- nextsong
- showtext
- hidetext
- text <text>

### How would this idea / enhancement be beneficial?

So I know they're commands.

See also #478

**Comment by Benascor** [comment]
I'm assuming these would need to go in /data/tech/commands.ts?

**Comment by MattIPv4** [comment]
Yup, that's where all the commands live.

**Comment by Benascor** [comment]
Alright so nextsong can go under the Audio section. I'm thinking the text commands can go under Scenes, or we could do a new section for text.

Also, just to double check the args here:

!nextsong _Skips music to the next song_
!showtext _Shows text on stream_
!hidetext _Hides text on stream_
!text <text:String> _Sets the text to be displayed on stream_

**Comment by MattIPv4** [comment]
That all sounds fine/correct

**Comment by Benascor** [comment]
Cool, I can take this one. Do I just assign it to myself and make a branch?

**Comment by MattIPv4** [comment]
Yup, you'll need to fork and then you can create a branch and make your changes.
