### ISSUE TITLE
[Idea]: Make !feed command outside donos display feeder status

### ISSUE THREAD

**Issue by JosephLiza** [alveusgg/alveusgg#639]
### Describe your idea / enhancement

Instead of displaying a static message, mention in some way the current status of the feeder. 
If it could detect the feeder status and send conditional messages i would suggest something like
"Currently the feeder is empty/disabled, come back later and feed the pasture animals for 5 USD or 500 Bits by putting !feed in your cheer or donation" when empty and the current message if there isnt a problem. 
A simpler but not so elegant solution could be simply display the generic message and right after have the alveusGG account reply the feeder status as if the user put !feederstatus (Possible downside is it could be a little spammy and it usually takes a couple of seconds to reply the status so it might be overlooked specially if chat is active)

The last suggestion is to simply add "Use !feederstatus before donating to see if it's available" 

### How would this idea / enhancement be beneficial?

I keep seeing users donating bits to feed the pasture when it's empty, jammed or disabled. I think this is in part because there is no mention of the command !feederstatus anywhere (that i know of). 
Making it clear that the feeder is working or not will help in making no one feel let down.

**Comment by MattIPv4** [comment]
This isn't within the remit of the website/chatbot that we maintain, as the feeder is a separate system. I will pass this on to the Alveus team though.

**Comment by JosephLiza** [comment]
Sorry about that, thanks for passing it along!

**Comment by MattIPv4** [comment]
FYI, this change has now been made.
