### ISSUE TITLE
[Idea]: Add arrows for creator selector and position relative to carousel.

### ISSUE THREAD

**Issue by JosephLiza** [alveusgg/alveusgg#648]
### Describe your idea / enhancement

Add arrows you can click to navigate creators. The arrows should have 2 states, one for the ends and one for everywhere else. The end one could be smaller and with less color value, and the clickable one bigger and bolder. 
Also i would suggest adding a way of knowing where in the carousel you are relative to the rest. 

![Carousel Left](https://github.com/alveusgg/alveusgg/assets/166082954/8b2764cc-a5c6-4d4c-a059-e1b8ed1bec6a)

![Carousel mid](https://github.com/alveusgg/alveusgg/assets/166082954/2b1e53dc-d3a9-40e0-b420-735dfd177e11)

### How would this idea / enhancement be beneficial?

I feel like while Shift + Scroll and Drag are both good ways of moving, a lot of people will find it more natural in desktop to click an arrow at the end of the carousel. The second suggestion of place in carousel will help to reinforce the idea that there are more creators to search from and to "Ground" the carousel in some way. (Right now there are not that many creators outside the main view but some day there will be)

**Comment by JosephLiza** [comment]
i didn't know if i should add this to #646 as it's closely related. Decided to open a new issue when i decided it should be a good idea to have the position thingy (Sorry I'm new to github etiquette)

**Comment by MattIPv4** [comment]
I am against adding arrows here, I intentionally did not use the existing carousel component for this. I think arrows are excessive here, between being able to scroll if you're on mobile or desktop w/ a trackpad, and being able to drag on desktop with a mouse, I feel it is plenty accessible enough. Arrows to add clutter to the UI on the page, IMO.

**Comment by MattIPv4** [comment]
Some sort of minimal indicator of how far you're scrolled might be good to visually hint at the fact there are more, beyond the fade at the end that is already present. Just need to be very careful with how it is done, so it does not appear to be an actual scrollbar.

**Comment by JosephLiza** [comment]
I think my main concern right now is that i don't feel it's conveyed well enought that it's a carousel. The fade does help, but by itself i feel like it's a little bit lacking. The position indicator itself could be enough. Another idea could potentially add an slow autoscrolling which wouldn't add any UI.
Thanks for the feedback. I will look at references as to how it could be done in a subdued way and come back.
