### ISSUE TITLE
[Idea]: Show & Tell: Show number of post x of x (not seen on stream) in fullscreen mode

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#669]
### Describe your idea / enhancement

For stream it would be nice if the presenter could see at what post of how many they are (the ones not seen on stream). This could be where the camera lives in the bottom right.

### How would this idea / enhancement be beneficial?

Help estimate time left for stream etc.

**Comment by ACA30** [comment]
How should this be implemented? Check for number of posts since the latest post with `seenOnStream` flag?

**Comment by MattIPv4** [comment]
Yeh, get the number of posts since the most recent `seenOnStream`, and then just track how many posts from the top the viewer is client-side and show that alongside the number fetched from the DB. Should only show in the presentation view, in the bottom right as noted above.
