### ISSUE TITLE
[Idea]: Found animal guides for rabbits, foxes, skunks and opossums 

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#676]
### Describe your idea / enhancement

Add more "found an animal" guides for these animals:

- [ ] rabbits
- [ ] foxes
- [ ] skunks
- [ ] opossums

Inspo:

- https://www.humanesociety.org/resources/found-orphaned-or-injured-baby-wild-animal#rabbits
- https://spca.bc.ca/faqs/i-found-baby-rabbit/

### How would this idea / enhancement be beneficial?

n/a

**Comment by loganrx8** [comment]
Will gladly take this on :) Was also thinking we could add Foxes, Opossums, Possums, Skunks, and possibly anymore you can think of?

**Comment by loganrx8** [comment]
Want to add Foxes, Skunks, Opossums as well :)
