### ISSUE TITLE
[Idea]: Replace Animated Webp Bell Peepo on Updates Page With Video or Still Image

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#698]
### Describe your idea / enhancement

The animated webp is pretty huge and apparently has problems playing at the correct fps. I would suggest replacing it with a webm video (~80% smaller) and fall back to a simple image. Maybe even supporting `prefers-reduced-motion`/`prefers-reduced-data`. I would not bother with HEVC + Alpha for older iOS.

### How would this idea / enhancement be beneficial?

Reduce bandwidth usage (for us and the users) - maybe even page responsiveness, improve accessibility.

**Comment by ACA30** [comment]
Do we _have_ access to a webm version somewhere? Converting it isn't super feasible - I tried a variety of strategies and none worked particularly well. If we have a file I'm happy in implement!

**Comment by MattIPv4** [comment]
Webm that should _hopefully_ perform better: [bellAlert.webm](https://github.com/user-attachments/assets/d204cbf6-6edb-4cda-bde1-23779aa81a88)

**Comment by pjeweb** [comment]
As @changesbyjames pointed out, the webm looks horrible in Safari (mac and ios). Did not catch this.
