### ISSUE TITLE
[Idea]: Add table of contents on pages with a lot of content/sections

### ISSUE THREAD

**Issue by Taizunz** [alveusgg/alveusgg#699]
### Describe your idea / enhancement

I'd love to see a table of contents out to the side of the page or at the top of the page when viewing a page that has a lot of content/sections on it, with the ability to click individual entries to quickly navigate to that part of the page.

### How would this idea / enhancement be beneficial?

It would allow visitors to quickly get an overview of the contents of the page at a glance without having to scroll through the entire page.

**Comment by MattIPv4** [comment]
👀 If we do want to this (not 100% sure we have many pages where this'd make a lot of sense, but perhaps the collab/AQ pages for the year headings and the category headings on the ambassadors page etc.), we can probably abstract and re-use what was implemented in #762

**Comment by alisondy** [comment]
Hi! I would like to pick up this issue
