### ISSUE TITLE
Set up pre-commit hooks for linting and code formatting

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#71]
run eslint & prettier on staged files

**Comment by MattIPv4** [comment]
I would recommend using https://github.com/okonet/lint-staged for this (they have an example for running prettier + eslint in the README), as it'll reduce system load by only linting what's being committed rather than everything every time.

**Comment by pjeweb** [comment]
There also is a snippet how to use `next lint` with lint-staged: https://nextjs.org/docs/basic-features/eslint#lint-staged and  https://github.com/okonet/lint-staged#integrate-with-nextjs
