### ISSUE TITLE
[Idea]: Mastodon/Fediverse integration

### ISSUE THREAD

**Issue by alok0** [alveusgg/alveusgg#719]
### Describe your idea / enhancement

Post to the fediverse with the same content as posted on twitter. Also post notifications.

Using one of the big public mastodon servers would be easy to setup.

### How would this idea / enhancement be beneficial?

This would allow people who avoid twitter/x to still receive posts.

**Comment by MattIPv4** [comment]
👋 we don't run the socials for Alveus, but I will pass this suggestion on to the Alveus team for consideration.
