### ISSUE TITLE
[Bug]: No navigation bar on large screens

### ISSUE THREAD

**Issue by JJeeff248** [alveusgg/alveusgg#733]
### What is the current behavior?

There is no navigation bar when viewing the website on larger screens/windows.
![image](https://github.com/user-attachments/assets/d89df763-efe4-44a1-b34a-9ebac9cf4368)

Changing my window size reveals the nav burger menu where I can then access the whole nav.
![image](https://github.com/user-attachments/assets/d1bea2c4-4a23-4f10-be01-b6bc8cc55d57)

### What is the expected behavior?

There should be a nav bar for all screen sizes.

### Steps to reproduce

Go to https://www.alveussanctuary.org/ on a large screen and look at the top where the nav bar should be. My screen is 1920x1080

### Browser specs

https://www.whatsmybrowser.org/b/TGN2T

**Comment by MattIPv4** [comment]
If you open up dev tools (ctrl + alt + i), in the console tab type in `document.querySelector('#main-nav').parentElement`. Hopefully that then responds with an HTML element. Right click on that and select reveal in elements panel. Can you send a screenshot of the dev tools window with that element selected?

![image](https://github.com/user-attachments/assets/04d9a17b-5cf2-4d90-a54d-9cfe6948df5e)

---

Are you able to reproduce this in a different browser, or in an incognito window?

**Comment by JJeeff248** [comment]
It seems my dark mode extension also uses the `.hidden` class overwriting the media query. Removing the extension from chrome fixes the issue. Sorry for the panic 😅
![image](https://github.com/user-attachments/assets/445da410-5902-4af7-be37-04a1a193ca7a)

**Comment by MattIPv4** [comment]
Ahah, that's fun! Yeah, I don't think there is a good way for us to get around that unfortunately. I'll close this but do feel free to shout if you can think of anything we can do to improve this for folks using funky extensions.
