### ISSUE TITLE
[Idea]: Add special zoo field to Show & Tell

### ISSUE THREAD

**Issue by ACA30** [alveusgg/alveusgg#738]
### Describe your idea / enhancement

With more and more people submitting Show & Tells from zoos - we should add a field where people can input a zoo name (autosuggest AZA zoos) and automatically list a "Verified AZA Zoo" badge or something on the frontend if it's an AZA zoo.

Allow mods to manually assign the badge for zoos that meet CAZA/EAZA/etc standards (or find some solution to also include those zoos in the autofill).

### How would this idea / enhancement be beneficial?

Reduce the amount of work for mods, searching up if zoos are AZA compliant.

**Comment by MattIPv4** [comment]
Closing per https://github.com/alveusgg/alveusgg/pull/739#issuecomment-2336402512
