### ISSUE TITLE
[Idea]: Add button to Discord notifications

### ISSUE THREAD

**Issue by ACA30** [alveusgg/alveusgg#747]
### Describe your idea / enhancement

Add button component to notification Discord webhook

NOTE: requires application-owned webhook.

https://discord.com/developers/docs/resources/webhook#execute-webhook
https://discord.com/developers/docs/interactions/message-components#component-object

### How would this idea / enhancement be beneficial?

Easier, more clear access to the CTA link

**Comment by ACA30** [comment]
@MattIPv4 is it feasible for you guys to get an app-owned webhook? Not sure if there's already a Discord bot that you own in the server...

**Comment by MattIPv4** [comment]
👀 I think to keep things simple for now, let's stick with a standard webhook that doesn't need a bot account -- I feel between the title being clickable and the link being in the embed body as well, there's enough clickable bits already. Appreciate the idea though!
