### ISSUE TITLE
[Idea]: Default pictures for "show" notifications (Animal Care Chats, Projects w/ Connor etc.)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#758]
### Describe your idea / enhancement

I think it would be nice to actually have cover images/posters for the recurring "shows" so we can actually make the embeds looks good (see #740).

For the admin panel that could be buttons, but for the `!notify` command we would need to find an easy way. Maybe we can use specific titles (or parts of it) to select the default image? For this it might make sense to use Fossabot commands to set title (and category and maybe a tag) so you can just use `!notify` without parameters?

### How would this idea / enhancement be beneficial?

Make notifications looks more nice :)

**Comment by MattIPv4** [comment]
These now exist (extracted frames from all the intros):

| | |
|-|-|
| <https://files.alveus.site/intros/connor.png> | ![](https://files.alveus.site/intros/connor.png) |
| <https://files.alveus.site/intros/nick.png> | ![](https://files.alveus.site/intros/nick.png) |
| <https://files.alveus.site/intros/animalcarechats.png> | ![](https://files.alveus.site/intros/animalcarechats.png) |
| <https://files.alveus.site/intros/chatchats.png> | ![](https://files.alveus.site/intros/chatchats.png) |
| <https://files.alveus.site/intros/pobox.png> | ![](https://files.alveus.site/intros/pobox.png) |
| <https://files.alveus.site/intros/alveus.png> | ![](https://files.alveus.site/intros/alveus.png) |

**Comment by MattIPv4** [comment]
I've updated all the `!set<whatever>` commands in Fossabot to include a default `!notify` command that includes these images, which any mod can then `!confirm` (#769).

**Comment by pjeweb** [comment]
Great solution. I think we can close this then, right?

**Comment by MattIPv4** [comment]
Did we want easy access to these in the admin UI, or is the main interface fine to be chat commands here (I think so given the images are used in the context of mitigations for regular streams)?

**Comment by pjeweb** [comment]
> Did we want easy access to these in the admin UI, or is the main interface fine to be chat commands here (I think so given the images are used in the context of mitigations for regular streams)?

Yeah i think if not seen anyone use the UI, so I think this is good as it is!?
