### ISSUE TITLE
[Idea]: Announcements/Notifications with scheduled dates should last till the end of event

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#772]
### Describe your idea / enhancement

Right now notifications last 30 minutes and announcements last 5 days until they are considered expired. Expired notifications will be remove from the announcement list and are to be hidden from end user devices that get them though web push (although I think Android and iOS do not really respect that). They will also not be retried to be delivered.

When an event is scheduled, I think the notifications/announcement should expire at the end of the event (or the end +30mins for notifications and +2h for announcements).

### How would this idea / enhancement be beneficial?

Keep announcements and notifications active longer.

**Comment by MehediMubin** [comment]
Hey @pjeweb,
Can you please assign this task to me?
Thanks

**Comment by pjeweb** [comment]
> Hey @pjeweb, Can you please assign this task to me? Thanks

Sure. Let me know if you need anything.

**Comment by MattIPv4** [comment]
👋 @MehediMubin any update on this? I'd like to let someone else work on this if you're not planning to get a PR opened soon.

**Comment by MehediMubin** [comment]
Can you give me two more days please?

**Comment by MattIPv4** [comment]
👋 @MehediMubin checking in again?
