### ISSUE TITLE
[Idea]: Change calendar layout based on user locale

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#777]
### Describe your idea / enhancement

The schedule should show weeks based on the user locale starting on Monday or Sunday. This should be available through for example: https://moment.github.io/luxon/#/intl?id=accessing-locale-based-week-info

I am not sure if it should always be US calendar for the alveus time, i would think not. Instead show both timezones with the week matching the users locale.

### How would this idea / enhancement be beneficial?

Better UX

**Comment by MattIPv4** [comment]
Sure 👍
