### ISSUE TITLE
[Idea]: Restyling the footer part

### ISSUE THREAD

**Issue by ayush-848** [alveusgg/alveusgg#785]
### Describe your idea / enhancement

To add some more padding and reordering the items

### How would this idea / enhancement be beneficial?

It will enhance the overall web design

**Comment by ayush-848** [comment]
Please assign this issue to me

**Comment by ayush-848** [comment]
@MattIPv4 
![image](https://github.com/user-attachments/assets/389f92e6-58a4-4c94-a452-192ede237835)
I was talking about this part.
I want to increase the height of the footer
And I will regroup the elements in a better way

**Comment by MattIPv4** [comment]
Okay, feel free to create a PR, but please understand there is no guarantee it will be accepted, I do think the footer is quite fine as it is.

**Comment by MattIPv4** [comment]
👋 @ayush-848 any update on this? I'd like to let someone else work on this if you're not planning to get a PR opened soon.

**Comment by ayush-848** [comment]
> 👋 @ayush-848 any update on this? I'd like to let someone else work on this if you're not planning to get a PR opened soon.

@MattIPv4 assign some one else for it.

**Comment by MattIPv4** [comment]
👍 I think am going to close this as it was something you filed yourself, and I don't think there is context/desire for others to work on it.
