### ISSUE TITLE
[Idea]: Go through collaborations and update popularity (followers)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#787]
### Describe your idea / enhancement

Go through the collaborations and update follower numbers. Most of them are very similar still, but some made big jumps. https://github.com/alveusgg/alveusgg/blob/main/apps/website/src/data/collaborations.ts#L67

### How would this idea / enhancement be beneficial?

Better highlight collaborations of (now) popular content creators.

**Comment by shradiphylleia** [comment]
@pjeweb just a quick check.... would you want me to manually change them or maybe write script to update them dynamically (have not figured this out just yet but this might be a good idea)

**Comment by pjeweb** [comment]
> @pjeweb just a quick check.... would you want me to manually change them or maybe write script to update them dynamically (have not figured this out just yet but this might be a good idea)

I'm not sure a script is worth the effort 🤷  I think we mostly have Twitch and Youtube content creators, but ideally we'd also check IG, TikTok etc. for their biggest "reach". I'd accept either, I think, but social media APIs tend to break or change every now and then. So maybe we just do it manually every 6 months or so.

**Comment by shradiphylleia** [comment]
@pjeweb thanks for the reply. the most popular of their socials should work about fine then. Later maybe looking for a 3rd party api which could fetch the info might work but for now I will do it manually based on the most popular of their social. Let me know if it works.

**Comment by MattIPv4** [comment]
You can probably just use whichever social platform is currently referenced for each one, just update the actual number and the date it was updated :)

**Comment by shradiphylleia** [comment]
@MattIPv4 Done with the rest.
Would need clarity regarding the collaborator Jack Manifold they have two entries:
https://github.com/alveusgg/alveusgg/blob/70eec19868987f928c9a24f5888ae463bc7b1d93/apps/website/src/data/collaborations.ts#L647  

https://github.com/alveusgg/alveusgg/blob/70eec19868987f928c9a24f5888ae463bc7b1d93/apps/website/src/data/collaborations.ts#L237 (recent collab)

should I do away with the previous collab entry? let me know and I will raise a PR. thanks

**Comment by MattIPv4** [comment]
No, he is in there twice because he has had two collaborations (as the comment explains), but we only store his creator details for the most recent one so he doesn't show up in the creator list twice.
