### ISSUE TITLE
Project basics (license, contribution guide etc.)

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#79]
- [x] Add some license (MIT or more strict?)
- [x] Add contribution guide (CONTRIBUTING.md)
  - Questions, Issues, Feature requests, Development, commit messages, pull requests, releases, tests?
- [x] Community guidelines/Code of Conduct? (maybe [Contributor Covenant](https://www.contributor-covenant.org/))
- [x] SECURITY.md?
- [ ] Labeling issues -> First time etc.
- [x] Templates for issues/PR?
- [x] Improve README
  - [x] Move `apps/website/README.md` into the main readme?
  - [x] Link to CONTRIBUTING.md
  - [x] Link to CoC

**Comment by pjeweb** [comment]
@MattIPv4 should we do some of these soon (mostly license and CoC) or is it not as important?  I'm usually just using or contributing to OSS ...  If so, do you have suggestions?

**Comment by MattIPv4** [comment]
I was going to write up a message for the Discord channel later today around a few of those.

Yeah, we should look at adding a license to the repos, but I want to check with folks about licensing for images specifically. I'm less worried about a CoC, but if we do we can add it to the .github repo to make it global. I think having a contributing.md would be nice, but with the setup details in the readme already pretty solid I think it's less of an issue (and our org-wide readme links to general guidance on contributing). I agree we should have a security.md (and a security.txt on the site), but we'll want a dedicated contact email for it which I'll ask about in Discord.

**Comment by pjeweb** [comment]
Good point about the content/image rights.

**Comment by pjeweb** [comment]
Same probably goes for the wordmarks "Alveus"/"Alveus Sanctuary"/"Alveus Sanctuary Inc.".

**Comment by nslee333** [comment]
Are all of these tasks still relevant? I want to check before I start working on them.

If they are I'll start working through the bullet points for CONTRIBUTING.md.

I'll probably need a decent amount of input but I'll make it happen.

**Comment by MattIPv4** [comment]
It looks like one of the README items was done (combining them), but otherwise I think everything here is still accurate (cc @pjeweb?)

**Comment by nslee333** [comment]
Alright I'll hold off on the README until @pjeweb confirms. 

So I got a few questions before I start a draft of contributing.md

### Questions:
- Where do you want people to post questions? Issues or discussions?
### Issues:
 -  Do you guys have any input on a bug reporting format? 
      -  Maybe `title`, `description`, `steps to reproduce (if any)` and `browser that is being used`.
 - Ideas / enhancements / feature requests format
      - Maybe something like `title`, `idea`, and `how it would improve life / product`? I'm not sure if a format is really necessary

### Commit messages
- Any preference? - maybe a short description of changes? 
### PRs
- Format: `title`, `description`, `reference issue that PR resolves`, 

Not sure what I need to put in there for releases and tests? What do I need to include for those?

**Comment by MattIPv4** [comment]
> Where do you want people to post questions? Issues or discussions?

On the issue they have a question about :) Or a discussion if there isn't a specific issue.

> Do you guys have any input on a bug reporting format? 

I think the fields you have make sense. In the description, I would prompt the user for expected/current behaviour, and maybe screenshots. For the browser in use, I'd point the user to https://www.whatsmybrowser.org/ for the browser field.

> Ideas / enhancements / feature requests format 

Title + description + justification sounds right 👍 

> Commit messages

I don't have a personal preference here, I've never been a fan of conventional commits etc. I just like them to be concise messages that clearly explain the diff. And for commits themselves, I like them to be isolated units of change, preferring more commits over less.

> PRs

Title + description of change + notes for testing the change + reference to an issue if there is one (using [GitHub keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) so it auto-links/closes).

> Not sure what I need to put in there for releases and tests? What do I need to include for those?

@pjeweb might be able to speak more to what we want testing for (we don't have many tests currently). And they might be able to give context on releases (not sure what it was referring to in the original message here).

**Comment by pjeweb** [comment]
Sorry for not responding to the questions. I hope to find some time early next week. Just in general I would keep it simple and easy to follow since we are not that big of a project. Main goal should be to encourage contribution and not strict rules. Testing in particular should probably not be required unless its an important part of code and fairly straight forward to test as a unit test (probably not UI). We don't really have a setup for integration tests or end-to-end tests.

**Comment by nslee333** [comment]
Okay cool, I got a draft PR #343 going for this task. Would you prefer that I open separate PRs for each task, or one PR just for this issue? 

> Testing in particular should probably not be required unless its an important part of code and fairly straight forward to test

Fair enough, How would you define important vs non-important? I can probably add something along the lines of 

`Unit Testing is encouraged but not required, if the code is important, and is straight forward to test, go for it otherwise it's not required.`

**Comment by nslee333** [comment]
Alright what else needs to be done on this one? @pjeweb @MattIPv4

**Comment by MattIPv4** [comment]
I think we've probably done everything here that we're going to do? I think a lot of our issues are more labelled now, and the issue templates will help with that going forward.
