### ISSUE TITLE
Standardise icons and icon sources

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#80]
We should standardise how we keep and use icons.

Currently we have:
- `src/icons/xxx.tsx` (inline svg icons as react components)
- `src/assets/icons/xxx.svg` (svg icons, included via URL)
- `simple-icons` (npm dep; simple icons for various brands, included via URL)
- `@heroicons/react`(npm dep; icon pack related to tailwind/tailwind ui, included via URL)

**Comment by tomheaton** [comment]
happy to do this 👀
