### ISSUE TITLE
Provide local dev stack

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#81]
- [ ] provide a docker compose or similar with required services 
  - [x] database => mysql
  - [x] s3 compatible file storage => minio/localstack
  - [ ] cronjob => ?

**Comment by MattIPv4** [comment]
@pjeweb do we need a local replacement for crons? You can always just hit `localhost:3000/api/cron` to trigger it manually I believe. If we do, we could use https://www.npmjs.com/package/vercel-cron, but it seems excessive?

**Comment by pjeweb** [comment]
Agreed. Not necessary.
