### ISSUE TITLE
[Bug]: Share thing in announcements gets cut off

### ISSUE THREAD

**Issue by JonasFranke** [alveusgg/alveusgg#822]
### What is the current behavior?

The share thing that opens when being clicked is cut off by the stay updated thing.
![image](https://github.com/user-attachments/assets/d81f96c0-9340-4817-8485-34960f306bb9)

### What is the expected behavior?

The share thing should be fully shown

### Steps to reproduce

1. Open https://www.alveussanctuary.org/updates#announcements
2. Click on share

### Browser specs

https://www.whatsmybrowser.org/b/C5Q8U

### Anything else?

On smaller screens it works as expected and the share thing stays on top

**Comment by alisondy** [comment]
Hi! I would like to work on this ☺️
