### ISSUE TITLE
Design: Apple Icon

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#90]
To me the current apple-touch-icon does look wrong, even though it is perfectly centred.
I would propose moving the logo in the icon to the top left a bit:

| Current  | Proposed |
| ------------- | ------------- |
| ![apple-touch-icon](https://user-images.githubusercontent.com/684458/223524051-2d93c5ab-ace6-404b-9512-0e24cb41fb21.png)  | ![apple-touch-icon-500](https://user-images.githubusercontent.com/684458/223524110-561a49a7-bd05-40c6-bcfb-e2de59bc46c4.png) |

**Comment by MattIPv4** [comment]
It might be worth putting some overlayed guide lines here to check the centering -- I think ideally we want the main oblong body (microphone bit) to be perfectly centered, irrespective of the decoration on top (the bird + swoop).

**Comment by pjeweb** [comment]
your version was perfect, but simply does look wrong to be when installed on the phone ...

**Comment by MattIPv4** [comment]
I'm not sure the current version is perfect -- I think its centered on the whole image, not just the oblong bit

**Comment by pjeweb** [comment]
yeah sorry I typed too fast. it was centred horizontally, but not vertically. Will properly check again later

**Comment by MattIPv4** [comment]
So I believe this should be centered based on the core part of the logo

![Logo](https://user-images.githubusercontent.com/12371363/223526375-218f7229-e886-460f-ae7e-d0d9fc47ce74.png)

**Comment by pjeweb** [comment]
Thank you! Yeah i checked. I still prefer the imperfect version, sorry :) Nothing too important but the "right" version just looks so wrong to me.

![alveus-icon](https://user-images.githubusercontent.com/684458/224397219-0323d302-5354-499b-8b1b-6b399ceddc78.png)

**Comment by MattIPv4** [comment]
How does this look if you try it:

![image](https://user-images.githubusercontent.com/12371363/224403207-2a939fe7-8520-4bb1-a49c-a5babbfecae5.png)

I've adjusted the vertical alignment to include the swoosh at the top, which is probably where the extra visual weight is coming from?

![image](https://user-images.githubusercontent.com/12371363/224403423-e289cbba-39e3-4e9a-b10c-3205b6a5eb34.png)

Fwiw, I agree with having it visually centered, I just want it in a reproducible way.
