### ISSUE TITLE
Conservation Cast Page

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#91]
- Shrez has a youtube playlist -> Overview like the Collaborations
- Link to website https://conservationcast.com/ or Anchor.fm/Spotify

**Comment by MattIPv4** [comment]
Having a page with all the embeds rather feels like we'd be stepping on the toes of the conservation cast website itself? If anything, I think we'd just want to surface the link somewhere (though it's not actually Alveus, so maybe on the About Maya page?)

**Comment by pjeweb** [comment]
Yep I thought the same, but the podcast page embeds twitch vods, not youtube videos  (= no adsense, no youtube views). Maybe we can fix the podcast site though?!

**Comment by MattIPv4** [comment]
Yeah, that feels like something worth flagging to whoever looks after that site.

**Comment by pjeweb** [comment]
Apparently the conservationcast.com website does not work anymore. I think I'll close this issue for now as it is not really related to Alveus.
