### ISSUE TITLE
Website: short link / page with P.O. box info

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/alveusgg#96]

**Comment by MattIPv4** [comment]
Might make sense to have on https://alveus.gg/contact-us and on https://alveus.gg/donate ?

**Comment by MattIPv4** [comment]
Or maybe even just donate (there is a nice gap for it), and have contact link back to there?

**Comment by pjeweb** [comment]
Sure donate page works. Right now the link tree links to the pinned post on twitter. I find that a bit silly ...
