### ISSUE TITLE
Encrypt PII at rest in the DB

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/alveusgg#97]
We should be encrypting PII in the DB to ensure that if the DB were popped there'd be no usable PII to extract.

https://www.npmjs.com/package/prisma-field-encryption might be a good candidate for doing this?

**Comment by pjeweb** [comment]
was about to link the same thing. I do however not think that encryption at rest is actually mandated or typical at least here in Germany

**Comment by MattIPv4** [comment]
Yah, I've not heard of it being mandated, but it seems like a good thing to do either way to keep the data a bit safer

**Comment by pjeweb** [comment]
i was lookingat this again. i am not fully convinced that `prisma-field-encryption` is worth it. it is quite a bit of code and deps. It is also not as easy to replace if want to use something other then prisma (which i might want). do you have a opinion on that?

my alternative suggestion would be to use WebCrypto and encrypt/decrypt on the app level. that would also work without prisma/nodejs e.g. in deno/edge functions. or using node's crypto package.

**Comment by MattIPv4** [comment]
👍 That concern makes sense to me, and using standard crypto to encrypt fields in the app itself makes sense to me
